# -*- coding: utf-8 -*-
"""20/4/2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uoIYxXZxH9DncEKNHdLSjfP3F082GIeh
"""

import pandas as pd

df = pd.read_csv("/content/Salary_Data (1).csv")

df

df.isnull().sum()

# replacing null values with mode and mean
for column in df.columns:
  if df[column].dtype == 'object':
    #fill categorical columns with the mode
    df[column] = df[column].fillna(df[column].mode()[0])
  else:
    #fill numerical columns with the mean
    df[column] = df[column].fillna(df[column].mean())
print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

#crucial thing for model
label_encoder =LabelEncoder()
for column in [ 'Gender', 'Education Level', 'Job Title']:
  df[column] = label_encoder.fit_transform(df[column])
print(df.head())

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Input features (X) head:")
display(X.head())

print("\nOutput target (y) head:")
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Import necessary metrics for evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(model_name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    print(f"--- {model_name} Performance ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"Mean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")

"""### 1. Linear Regression"""

from sklearn.linear_model import LinearRegression

# Initialize and train the model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions
y_pred_lr = linear_model.predict(X_test)

# Evaluate the model
evaluate_model("Linear Regression", y_test, y_pred_lr)

"""### 2. Support Vector Regressor (SVR)"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# Scaling features for SVR
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the model
# Using a small C value and 'linear' kernel for initial demonstration
# Due to potential long training time with default RBF and large dataset
svr_model = SVR(kernel='linear', C=100)
svr_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_svr = svr_model.predict(X_test_scaled)

# Evaluate the model
evaluate_model("Support Vector Regressor", y_test, y_pred_svr)

"""### 3. K-Nearest Neighbors Regressor"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the model
knn_model = KNeighborsRegressor(n_neighbors=5) # You can adjust n_neighbors
knn_model.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
evaluate_model("K-Nearest Neighbors Regressor", y_test, y_pred_knn)

"""### 4. Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the model
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = dt_model.predict(X_test)

# Evaluate the model
evaluate_model("Decision Tree Regressor", y_test, y_pred_dt)

"""### 5. Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # n_estimators can be adjusted
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
evaluate_model("Random Forest Regressor", y_test, y_pred_rf)

"""### Visual Comparison of Model Performance"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Collect the metrics for each model
model_names = ['Linear Regression', 'Support Vector Regressor', 'K-Nearest Neighbors Regressor', 'Decision Tree Regressor', 'Random Forest Regressor']

# Assuming y_test and y_pred_lr, y_pred_svr, y_pred_knn, y_pred_dt, y_pred_rf are already defined
metrics = []

# Linear Regression metrics (from execution output: MAE: 23736.65, MSE: 892668414.69, RMSE: 29877.56, R2: 0.67)
metrics.append({
    'Model': 'Linear Regression',
    'MAE': 23736.65,
    'MSE': 892668414.69,
    'RMSE': 29877.56,
    'R2': 0.67
})

# SVR metrics (from execution output: MAE: 23097.36, MSE: 1017437628.90, RMSE: 31897.30, R2: 0.62)
metrics.append({
    'Model': 'Support Vector Regressor',
    'MAE': 23097.36,
    'MSE': 1017437628.90,
    'RMSE': 31897.30,
    'R2': 0.62
})

# KNN metrics (from execution output: MAE: 4207.87, MSE: 101306941.19, RMSE: 10065.13, R2: 0.96)
metrics.append({
    'Model': 'K-Nearest Neighbors Regressor',
    'MAE': 4207.87,
    'MSE': 101306941.19,
    'RMSE': 10065.13,
    'R2': 0.96
})

# Decision Tree metrics (from execution output: MAE: 3116.94, MSE: 93817976.26, RMSE: 9685.97, R2: 0.96)
metrics.append({
    'Model': 'Decision Tree Regressor',
    'MAE': 3116.94,
    'MSE': 93817976.26,
    'RMSE': 9685.97,
    'R2': 0.96
})

# Random Forest metrics (from execution output: MAE: 3152.26, MSE: 65085758.85, RMSE: 8067.57, R2: 0.98)
metrics.append({
    'Model': 'Random Forest Regressor',
    'MAE': 3152.26,
    'MSE': 65085758.85,
    'RMSE': 8067.57,
    'R2': 0.98
})

performance_df = pd.DataFrame(metrics)
display(performance_df)

# Sort by R2 score for better visualization
performance_df_sorted_r2 = performance_df.sort_values(by='R2', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='R2', data=performance_df_sorted_r2, hue='Model', palette='viridis', legend=False)
plt.title('Model Comparison - R-squared (R2) Score')
plt.xlabel('Model')
plt.ylabel('R-squared Score')
plt.ylim(0, 1) # R2 score is between 0 and 1
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Sort by MAE score for better visualization (lower MAE is better)
performance_df_sorted_mae = performance_df.sort_values(by='MAE', ascending=True)

plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='MAE', data=performance_df_sorted_mae, hue='Model', palette='plasma', legend=False)
plt.title('Model Comparison - Mean Absolute Error (MAE)')
plt.xlabel('Model')
plt.ylabel('Mean Absolute Error')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import joblib

# Define the filename for the saved model
model_filename = 'random_forest_regressor_model.pkl'

# Save the Random Forest Regressor model
joblib.dump(rf_model, model_filename)

print(f"Best model (Random Forest Regressor) saved as {model_filename}")

"""You can download the `random_forest_regressor_model.pkl` file from the file browser on the left sidebar (Files icon > right-click on the file > Download)."""
